### ISSUE TITLE
Create a Heroku Account

### ISSUE THREAD

**Issue by LGKev** [LGKev/CSDev_Code#9]
I am not 100% sure yet, but it looks like to collaborate on Heroku we need to create accounts. and add our emails to a project. I created an account to try to start making a database on heroku. If you could comment back the email you used I can add it to the collaborators tab.

**Comment by LGKev** [comment]
kwat100br@gmail.com

**Comment by bittybueno** [comment]
marissa.bueno21@gmail.com - So I can configure the app the server (i'll try to get it done today) and you can handle the  Postgres database add-on @LGKev ? Check this out https://medium.com/@aem_iro/deploying-a-node-js-postgressql-app-to-heroku-hosting-platform-cc611287ae76 . It highlights the integration for Heroku

**Comment by LGKev** [comment]
@bittybueno  yep! I am struggling my way through now!

**Comment by bittybueno** [comment]
Awesome! Just trying to make sure where all on the same page. Let me know if you need help!

**Comment by dech9329** [comment]
Hey Kevin! Here's the email I used: chende21@aol.com

**Comment by LGKev** [comment]
@bittybueno I think you can now add your app to the team heroku

**Comment by mdvuco** [comment]
mavu2562@colorado.edu

**Comment by eliberumen27** [comment]
eliberumen27@gmail.com
